CREATE TABLE `users` (
  `userId` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `isAdmin` tinyint NOT NULL DEFAULT '0',
  `username` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firstName` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastName` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `avatarFileId` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bio` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dob` date NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `addressStreet` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `addressCity` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `addressZip` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `addressState` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `addressCounty` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `addressLat` decimal(10,7) DEFAULT NULL,
  `addressLng` decimal(10,7) DEFAULT NULL,
  `optInUpdates` tinyint(1) DEFAULT '0',
  `agreedToTerms` tinyint(1) DEFAULT '0',
  `consentSms` tinyint(1) DEFAULT '0',
  `emailVerified` bigint DEFAULT NULL,
  `phoneVerified` bigint DEFAULT NULL,
  `created` bigint NOT NULL,
  `lastLogin` bigint DEFAULT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `idx_users_username` (`username`),
  KEY `idx_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci